# Generated by Django 3.2.6 on 2021-09-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0002_auto_20210904_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='solid_waste',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='solid_waste'),
        ),
        migrations.AddField(
            model_name='waste_container',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='waste_container'),
        ),
    ]
