# Generated by Django 3.2.6 on 2021-10-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0003_auto_20210906_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='solid_waste',
            name='impact',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
