# Generated by Django 3.2.6 on 2021-11-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordatorio',
            name='dayOfTheWeek',
        ),
    ]
