# Generated by Django 3.2.6 on 2021-11-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorio', '0002_remove_recordatorio_dayoftheweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='diaSemana',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='martes', max_length=9),
        ),
    ]
